name: Manager CI

on:
  push:
    branches:
      - main
    paths:
      - 'apps/manager/**'
  pull_request:
    branches:
      - main
    paths:
      - 'apps/manager/**'

jobs:
  CI:
    uses: ./.github/workflows/ci.yml
    with:
      turbo-filters: '--filter=@powercoach/manager'
      workflow-name: Manager CI
    secrets:
      API_BASE_URL: ${{ secrets.GCR_API_URL }}
